# Generated by Django 3.1.1 on 2020-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
